version: '3'

services:

  nginx:
    image: nginx:latest
    volumes:
      - ./backend:/var/www
      - ./backend/docker/nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - ${NGINX_EXTERNAL_PORT}:80
    depends_on:
      - php
      - postgres
    container_name: lending_nginx

  php:
    build:
      args:
        user: lending
        uid: 1000
      context: ./backend
      dockerfile: docker/php/Dockerfile
    links:
      - postgres
    volumes:
      - ./backend/docker/php/php.ini:/usr/local/etc/php/conf.d/php-overrides.ini
      - ./backend:/var/www
    container_name: lending_php

  postgres:
    env_file: ./backend/.env
    image: postgres:14.3
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_EXTERNAL_PORT}:5432
    container_name: lending_postgre

  node:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - ${NODE_EXTERNAL_PORT}:3000
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    container_name: lending_node

volumes:
  db-data:
    driver: local
